backend:
  # name: 'git-gateway'
  name: github
  repo: 'OOKB/kinderplatz-api'
  app_id: '93b9c3d135179c9c8448c23655c3ba9f3aee70b016ce73b3abcb53f811771f73'
  branch: 'main'
  auth_endpoint: auth
  base_url: https://auth.cape.io/

site_domain: kinderplatz-api.pages.dev
# local_backend: true
# media_library:
#   name: uploadcare
#   config:
#     publicKey: 'ac121cbded935a504272'
media_folder: public/media
public_folder: /media
site_url: https://kinderplatz-api.pages.dev
collections:
  - label: Data
    name: 'data'
    files:
      - label: Sections
        name: sections
        file: content/data/sections.yaml
        fields:
          - label: Default Color
            name: color
            widget: select
            options: ['sky', 'orange', 'lime', 'fuchsia', 'yellow', 'red', 'pink']
          - label: Menu Length
            name: menuSize
            hint: The max number of sections to display in the top header menu.
            widget: number
            min: 2
            max: 8
          - label: Section Pages
            name: sections
            widget: list
            allow_add: true
            summary: "{{fields.page}}"
            fields:
              # - {label: } // reference
              - label: Section Page
                name: page
                widget: relation
                collection: pages
                search_fields: ['title']
                value_field: slug
                display_fields: ['title']
              - label: Section Color
                name: sectionColor
                widget: select
                # colors must match tailwind.config.cjs -> colorIds variable.
                options: ['sky', 'orange', 'lime', 'fuchsia', 'yellow', 'red', 'pink']
              - label: Title Override
                name: name
                widget: string
                required: false
              - label: Related Links
                name: links
                widget: relation
                collection: pages
                search_fields: ['title']
                value_field: slug
                display_fields: ['title']
                multiple: true
                required: false
              - label: "Images"
                name: "images"
                widget: list
                required: false
                max: 3
                fields:
                  - label: Image
                    name: src
                    widget: "image"
                    choose_url: true
                    required: true
                    media_library:
                      config:
                        multiple: true
                  - label: Alt Text
                    name: alt
                    widget: string
                    required: true

  - label: Pages
    name: "pages"
    folder: content/pages
    create: true
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Slug, name: slug, widget: string }
      - { label: "Body", name: "body", widget: "markdown" }
      - label: Related Links
        name: links
        widget: list
        fields:
          - { label: Name, name: name, widget: string }
          - { label: URL, name: href, widget: string }
